#
# Since: October 2024
# Author: gvenzl
# Name: test-action-script.yml
# Description: GitHub Actions Oracle load tests
#
# Copyright 2024 Gerald Venzl
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

name: Test action script 'setup-oracledb.sh'
on: [push, pull_request]

jobs:

  run-with-default-parameters:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Invoke script
        run : |
          export SETUP_HEALTH_MAX_RETRIES=10
          export SETUP_APP_USER="TEST"
          export SETUP_APP_USER_PASSWORD="LetsTest1"
          ./setup-oracledb.sh

  trigger-failure-with-invalid-app-user-password:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Invoke script
        run : |
          export SETUP_HEALTH_MAX_RETRIES=10
          export SETUP_APP_USER="SYS"
          export SETUP_APP_USER_PASSWORD="foo"
          # Negative test: setup is expected to fail
          #   If it fails, return 0 (success), if it succeeds, return 1 (failure)
          ./setup-oracledb.sh && exit 1 || exit 0

  test-with-container-network:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Invoke script
        run: |
          podman network create test-network
          export SETUP_CONTAINER_NETWORK="test-network"
          export SETUP_HEALTH_MAX_RETRIES=10
          export SETUP_APP_USER="TEST"
          export SETUP_APP_USER_PASSWORD="LetsTest1"
          ./setup-oracledb.sh
